### PR TITLE
404

### PR DESCRIPTION
**Pull request by Mattsface**
### Why
As a developer and user, I want consistent and specified return statements for each function

### What
Added a 404 test that will return None, empty list, and empty dict

### Tests
PyTest

### Risk and impact
What is the risk level of the change and **why?**
- Minimal

What is the impact if something does go wrong with this PR?

### CODE REVIEW

**Comment by KCNilssen** [comment]
Hey don't we already check for a 404 error? We then check for the empty return with the if person in data and others like that?

https://github.com/zero-sum-seattle/python-mlb-statsapi/blob/c5fae343f9dbda02caa9f320045f55f8380ce213/mlbstatsapi/mlb_dataadapter.py#L126

**Comment by Mattsface** [comment]
> 

@KCNilssen we do check for 400 errors in the MLB Adapter, but then we just pass on as a MlbResult with an empty dict.

**Comment by Mattsface** [comment]
> Hey don't we already check for a 404 error? We then check for the empty return with the if person in data and others like that?
> 
> https://github.com/zero-sum-seattle/python-mlb-statsapi/blob/c5fae343f9dbda02caa9f320045f55f8380ce213/mlbstatsapi/mlb_dataadapter.py#L126

https://github.com/zero-sum-seattle/python-mlb-statsapi/blob/404/mlbstatsapi/mlb_api.py#L84-L85

The key checking is too check for when the REST API returns a 200, but leaves the 'person' key an empty list.

**Comment by Mattsface** [comment]
This will be nice because it'll be very apparent in our code what the function returns, a object, or list, None, and empty list.

**Review by KCNilssen — APPROVED** [review]
LGTM

**Pull request merged**
